---
title: "equations"
author: "group 2"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# CONTACT RATES

\begin{align*}
c_{f, internal} &= \frac{c_{m, internal} \cdot m_{num}}{f_{num}} \\
c_{f, external} &= c_{m, external} \\
\end{align*}


# FORCE OF INFECTION
## UNVACCINATED

\begin{align*}
\lambda_{uv, g, external} &= \tau c_{g, external} I_{g*, external} \\
\lambda_{uv, g, internal} &= \tau c_{g, internal} \frac{i_{num, g*}}{n_{g*}} \\
\lambda_{uv,g} &= \lambda_{uv, g, external} + \lambda_{uv, g, internal} \\
\end{align*}



## VACCINATED


\begin{align*}
\lambda_{v, g, external} &= \tau (1 - \psi) c_{g, external} I_{g*, external} \\
\lambda_{v, g, internal} &= \tau (1 - \psi) c_{g, internal} \frac{i_{num, g*}}{n_{g*}} \\
\lambda_{v,g} &= \lambda_{v, g, external} + \lambda_{v, g, internal}
\end{align*}



# Susceptible Unexposed (For individuals aged 11-18 years):


\begin{align*}
& \frac{dU_{uv,g}}{dt} = 0.5 (1 - \omega_g \chi) \nu N - \alpha_{\text{in}} U_{g} - \mu_{u}U_{uv,g} \\
& \frac{dS_{g}}{dt} = \alpha_{\text{in}} U_{g} - \mu_{e} S_{g} - \alpha_{\text{out}} S_{g} - \lambda_{uv, g} Z  S_{g} - \lambda_{uv,g} (1 - Z) S_{g} + \delta_{uv,a} I_{uv,g,a} + \delta_{uv,s} I_{uv,g,s} - \kappa S_{g} \\
& \frac{dI_{uv,g,a}}{dt} = -\alpha_{\text{out}} I_{uv,g,a} - \mu_e I_{uv,g,a} + \lambda_{uv,g} (1 - Z) S_{g} - \delta_{g,a} I_{uv,g,a} \\
& \frac{dI_{uv,g,s}}{dt} = -\alpha_{\text{out}} I_{uv,g,s} - \mu_e I_{uv,g,s} + \lambda_{g,s} Z S_{g} - \delta_{uv,s} I_{uv,g,s} \\
\end{align*}



# VACCINATED ###############################################################################



\begin{align*}
& \frac{dU_{v,g}}{dt} = 0.5 \omega_g \chi \nu N - \alpha_{\text{in}} V_{g} - \mu_{u} U_{v,g} \\
& \frac{dV_{g}}{dt} = \alpha_{\text{in}} U_{v, g} - \alpha_{\text{out}} V_{g} - \mu_e V_{g} - \lambda_{v,g} Z V_{g} - \lambda_{v, g} (1 - Z) V_{g} + \delta_{v,a} I_{v,g,a} + \delta_{v,s} I_{v,g,s} + \kappa S_{g} \\
& \frac{dI_{v,g,a}}{dt} = -\alpha_{\text{out}} I_{v,g,a} - \mu_e I_{v,g,a} + \lambda_{v,g} (1 - Z)  V_{g} - \delta_{v,a} I_{v,g,a} \\
& \frac{dI_{v,g,s}}{dt} = -\alpha_{\text{out}} I_{v,g,s} - \mu_e I_{v,g,s} + \lambda_{v,s} Z V_{g} - \delta_{v,s} I_{v,g,s} \\
\end{align*}



