---
title: "Initial Model"
output: html_document
date: "2024-03-13"
---

```{r setup, include=FALSE}
#HELLO WORLD!

knitr::opts_chunk$set(echo = TRUE)

library(pacman)
library(EpiModel)
library(ggplot2)
library(tidyverse)
```

```{r 3 All or Nothing}
AoN <- function(t, t0, parms) {
  with(as.list(c(t0, parms)), {
    # 1.Track the population sizes
    h.num <- s.h.num + i.h.num + r.h.num + v.h.num
    l.num <- s.l.num + i.l.num + r.l.num + v.l.num
    y.num <- s.y.num + i.y.num + r.y.num
    num <- h.num + l.num + y.num
    
    # 2. Define Contact Rate for low-sexual activity based on the rate for high sexual activity. Define Contact Rate for young persons. I am giving young persons their own contact rate and they wont have contacts with the high and low sex activity groups.
      beta1 <- ce1 / h.num
      beta2 <- ce2 / num
      beta3 <- ce3 / y.num
      # we are assuming there is a higher contact rate between high-high contacts and then lower contact between the other 2 pairing of low-low, high-low.
      
#Can we make this assumption that the ce would be the same for these other ones
    
   # 3.Define lambda
      lambda.hh <- beta1 * i.h.num
      lambda.hl <- 0.5 * beta2 * i.l.num
      lambda.h <- lambda.hh + lambda.hl

      lambda.ll <- beta2 * i.l.num
      lambda.lh <- 0.5 * beta2 * i.h.num
      lambda.l <- lambda.ll + lambda.lh
      
      lambda.y <- beta3 * i.y.num


# Unsure on this (we have infection probability * contact rate times number of people infected overall???)
    
    mu.a <- 1/lifespan
    mu.y <- 1/childspan # I have no idea how to define death rate for 12-15 year olds
    gamma <- 1/dur.inf
    alpha <- 1/puberty_span
    # 3.Write eight differential equations
    
    #iota represents some parameter we need to represent the proportion of young people that become highly sexually active vs low sexual activity. set at 0.9
    #Assume that only susceptible young persons are getting vaccinated.
    #vaccine provides 100% protection so we dont need chi
    # we will model both vaccination of children and adults
    
    #Susceptibles
    dSh <- (-lambda.h * s.h.num) + (1-(alpha*s.y.num*(iota))) + ((1 - (omega.a)) * (mu.a * h.num)) - (mu.a * s.h.num) 
    dSl <- (-lambda.l * s.l.num) + (alpha*s.y.num*(iota)) + ((1 - (omega.a)) * (mu.a * l.num)) - (mu.a * s.l.num) 
    dSy <- (-lambda.y * s.y.num) - (alpha*s.y.num) - (mu.y * s.y.num) - (omega.y*s.y.num) 
    
    #Infected
    dIh <- (lambda.h * s.h.num)  + (1-(alpha*i.y.num*(iota))) - (gamma * i.h.num) - (mu.a * i.h.num) 
    dIl <- (lambda.l * s.l.num) + (alpha*i.y.num*(iota)) - (gamma * i.l.num) - (mu.a * i.l.num) 
    dIy <- (lambda.y * s.y.num) - (alpha*i.y.num) - (gamma * i.y.num) - (mu.y * i.y.num) 
    
    #Recovered
    dRh <- (gamma * i.h.num) + (1-(alpha*r.y.num*(iota))) - (mu.a * r.h.num) 
    dRl <- (gamma * i.l.num) + (alpha*r.y.num*(iota)) - (mu.a * r.l.num) 
    dRy <- (gamma * i.y.num) - (alpha*r.y.num) - (mu.y * r.y.num) 
    
    #Vaccinated
    dVh <- (omega.a * (mu.a)*(h.num)) - (mu.a * v.h.num) + (1-(omega.y*s.y.num*iota)) 
    dVl <- (omega.a * (mu.a)*(l.num)) - (mu.a * v.l.num) + (omega.y*s.y.num*iota)
    # 4.Outputs
    list(c(dSh, dSl, dSy,dIh, dIl, dIy, dRh, dRl, dRy, dVh, dVl, 
           si.h.flow = lambda.h * s.h.num,
           si.l.flow = lambda.l * s.l.num,
           v.h.flow = (omega.a * mu.a * h.num + (1-(omega.y * s.y.num * iota))),
           v.l.flow = (omega.a * mu.a * l.num + (omega.y * s.y.num * iota))
    ))
  })
}

param <- param.dcm(tau = 0.5, ce1 = 0.34, ce2 = 0.07, ce3 = 0.001, lifespan = (50*365), childspan = (80*365), puberty_span = (3*365),
                   dur.inf = 14, omega.a = 0.25, omega.y = 0.5, chi = 0.5, iota = 0.9)

init <- init.dcm(s.h.num = 100, s.l.num = 100, s.y.num = 100, i.h.num = 1, i.l.num = 1, i.y.num = 1, r.h.num = 0, r.l.num = 0, r.y.num =0, v.h.num = 0, v.l.num = 0,
                 si.h.flow = 0, si.l.flow = 0, v.h.flow = 0, v.l.flow = 0)

control <- control.dcm(nsteps = (5*365), new.mod = AoN)

mod <- dcm(param, init, control)
mod
```
```{r}
# Add number infected and prevalence
mod <- mutate_epi(mod, h.num = s.h.num + i.h.num + r.h.num + v.h.num, l.num = s.l.num + i.l.num + r.l.num + v.l.num)
mod <- mutate_epi(mod, h.prev = i.h.num / h.num, l.prev = i.l.num / l.num)


par(mfrow = c(2,2), mar = c(3,3,2,1), mgp = c(2,1,0)) 

plot(mod, y = "i.h.num", main = "number infected high_activity",
legend = "lim", lwd = 1)

plot(mod, y = "i.l.num", main = "number infected low_activity",
legend = "lim", lwd = 1)

plot(mod, y = "h.prev", main = "prev infected high_activity",
legend = "lim", lwd = 1, ylim = c(0, 0.5)) 

plot(mod, y = "l.prev", main = "prev infected low_activity",
legend = "lim", lwd = 1, ylim = c(0, 0.1))
```

