---
title: "Updated_Model0410_Full"
author: "Bevin Manuelpillai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(EpiModel)
library(ggplot2)
library(tidyverse)
library(tidyr)
library(reshape2)
library(dplyr)
library(metR)
library(viridis)
```

```{r}
#Update for BEVIN:
#uv.m.ue.num = s.m.ue.num
#uv.m.e.num = s.m.e.num
#i.m.uv.s.num= i.m.s.s.num
#uv.f.ue.num = s.f.ue.num
#uv.f.e.num = uv.f.e.num
#i.f.uv.s.num= i.f.uv.s.num

## there seems to be too many .num values. we have 8 compartments per sex, so seems like there should be 8 .num values contributing to m.num ?
## starting new document to go a little crazy testing things. we can decide what to keep/pitch later

Vaccination <- function(t, t0, parms) {
  with(as.list(c(t0, parms)), {
#1. Track Population Sizes
    #unvaccinated as S
m.num = uv.m.ue.num + uv.m.e.num + i.m.s.a.num + i.m.uv.s.num + v.m.ue.num + v.m.e.num + i.m.v.a.num + i.m.v.s.num + uv.m.e.num

f.num = uv.f.ue.num + uv.f.e.num + i.f.s.a.num + i.f.uv.s.num + v.f.ue.num + v.f.e.num + i.f.v.a.num + i.f.v.s.num + uv.f.e.num

num = f.num + m.num


i.m.num = i.m.s.a.num + i.m.uv.s.num+ i.m.v.a.num + i.m.v.s.num
i.f.num = i.f.s.a.num + i.f.uv.s.num + i.f.v.a.num + i.f.v.s.num
  
#2. Define Contact Rate
ce.f <- (ce.m * m.num) / f.num

#3. Define Lambda
  # For Susceptible Males
lambda.m.s.a <- (tau.s) * (ce.m) * (i.f.num / f.num)

  # For Susceptible Females
lambda.f.s.a <-  (tau.s) * (ce.f) * (i.m.num / m.num)
  
  # For Vaccinated Males
lambda.m.v.a <- (tau.v) * (ce.m) * (i.f.num / f.num)

# For Vaccinated Females
lambda.f.v.a <-  (tau.v) * (ce.f) * (i.m.num / m.num)


#4. Define Additional parameters
  delta.s.a <- 1/dur.inf.s.a
  delta.s.s <- 1/dur.inf.s.s
  #Vaccinated clears infections faster
  delta.v.a <- 1/dur.inf.v.a
  delta.v.s <- 1/dur.inf.v.s

#5. Define Differential Equations
  
#zeta is proportion of asymptomatic that become symptomatic at each timestep, 
#kappa is the proportion of susceptible exposed that become vaccinated exposed at each timestep
# nu is birthrate
# MALES
dS.m.ue <- ((0.5 * (1-omega.m) * chi * nu * num)) - (age.in * uv.m.ue.num) - (mu.ue * uv.m.ue.num)

dS.m.e <- (age.in * uv.m.ue.num) - (lambda.m.s.a * uv.m.e.num) + (delta.s.a * i.m.s.a.num) + (delta.s.s * i.m.uv.s.num) - (kappa.m * uv.m.e.num) - (age.out * uv.m.e.num) - (mu * uv.m.e.num)

dI.m.s.a <- (lambda.m.s.a * uv.m.e.num) - (zeta.s * i.m.s.a.num) - (delta.s.a * i.m.s.a.num) - (age.out * i.m.s.a.num) - (mu * i.m.s.a.num)

dI.m.s.s <- (zeta.s * i.m.s.a.num) - (delta.s.s * i.m.uv.s.num) - (age.out * i.m.uv.s.num) - (mu * i.m.uv.s.num)


dV.m.ue <- (0.5 * omega.m * chi * nu * num) - (age.in * v.m.ue.num) - (mu.ue * v.m.ue.num) 

dV.m.e <- (age.in * v.m.ue.num) - (lambda.m.v.a * v.m.e.num) + (delta.v.a * i.m.v.a.num) + (delta.v.s * i.m.v.s.num) + (kappa.m * uv.m.e.num) - (age.out * v.m.e.num) - (mu * v.m.e.num)

dI.m.v.a <- (lambda.m.v.a * v.m.e.num) - (zeta.v * i.m.v.a.num) - (delta.v.a * i.m.v.a.num) - (age.out * i.m.v.a.num) - (mu * i.m.v.a.num)

dI.m.v.s <- (zeta.v * i.m.v.a.num) - (delta.v.s * i.m.v.s.num) - (age.out * i.m.v.s.num) - (mu * i.m.v.s.num) 

# FEMALES
# should it just be (1-omega.f*chi) here? instead of the complement of the whole term?
dS.f.ue <- ((0.5 * (1-omega.f) * chi * nu * num)) - (age.in * uv.f.ue.num) - (mu.ue * uv.f.ue.num)

dS.f.e <- (age.in * uv.f.ue.num) - (lambda.f.s.a * uv.f.e.num) + (delta.s.a * i.f.s.a.num) + (delta.s.s * i.f.uv.s.num) - (kappa.m * uv.f.e.num) - (age.out * uv.f.e.num) - (mu * uv.f.e.num)

dI.f.s.a <- (lambda.f.s.a * uv.f.e.num) - (zeta.s * i.f.s.a.num) - (delta.s.a * i.f.s.a.num) - (age.out * i.f.s.a.num) - (mu * i.f.s.a.num)

dI.f.s.s <- (zeta.s * i.f.s.a.num) - (delta.s.s * i.f.uv.s.num) - (age.out * i.f.uv.s.num) - (mu * i.f.uv.s.num)


dV.f.ue <- (0.5 * omega.f * chi * nu * num) - (age.in * v.f.ue.num) - (mu.ue * v.f.ue.num) 

dV.f.e <- (age.in * v.f.ue.num) - (lambda.f.v.a * v.f.e.num) + (delta.v.a * i.f.v.a.num) + (delta.v.s * i.f.v.s.num) + (kappa.f * uv.f.e.num) - (age.out * v.f.e.num) - (mu * v.f.e.num)

dI.f.v.a <- (lambda.f.v.a * v.f.e.num) - (zeta.v * i.f.v.a.num) - (delta.v.a * i.f.v.a.num) - (age.out * i.f.v.a.num) - (mu * i.f.v.a.num)

dI.f.v.s <- (zeta.v * i.f.v.a.num) - (delta.v.s * i.f.v.s.num) - (age.out * i.f.v.s.num) - (mu * i.f.v.s.num)

# 6.Outputs
list(c(dS.m.ue, dS.m.e, dI.m.s.a, dI.m.s.s, 
       dV.m.ue, dV.m.e, dI.m.v.a, dI.m.v.s,
       dS.f.ue, dS.f.e, dI.f.s.a, dI.f.s.s, 
       dV.f.ue, dV.f.e, dI.f.v.a, dI.f.v.s,
       si.m.flow = (lambda.m.s.a * uv.m.e.num),
       vi.m.flow = (lambda.m.v.a * v.m.e.num),
       sv.m.flow = (kappa.m * uv.m.e.num),
       si.f.flow = (lambda.f.s.a * uv.f.e.num),
       vi.f.flow = (lambda.f.v.a * v.f.e.num),
       sv.f.flow = (kappa.f * uv.f.e.num))
       )
  })
}

```


```{r}
# Vaccination Scenario 1.) Male vaccination at birth increased from 0.1 to 0.8 by 0.2       
param <- param.dcm( tau.s = 0.74, tau.v = 0.31, ce.m = (5/365),
                    nu = (0.01/365), mu.ue = (0.0025/365), mu = (0.005/365),
                    dur.inf.s.a = (3*365), dur.inf.s.s= (1.5*365),
                    dur.inf.v.a = (3*365), dur.inf.v.s = (1.5*365),
                    age.in = (1/(8*365)), age.out = (1/(11*365)),
                    omega.m = seq(0.1,0.8, by = 0.2), omega.f = 0.40, chi = 0.90,
                    zeta.v = (0.1/365) , zeta.s = (0.1/365), kappa.m = (0.0025/365), kappa.f = (0.0025/365))

init <- init.dcm( # males
                 uv.m.ue.num = 1600000, uv.m.e.num = 3800000,
                 i.m.s.a.num = 1300000, i.m.uv.s.num= 1300000,
                 v.m.ue.num = 304000, v.m.e.num = 304000, 
                 i.m.v.a.num = 1300000, i.m.v.s.num = 1300000,
                 # females
                 uv.f.ue.num = 1700000, uv.f.e.num = 3800000, 
                 i.f.s.a.num = 3000000, i.f.uv.s.num = 3000000,
                 v.f.ue.num = 240000, v.f.e.num = 240000, 
                 i.f.v.a.num = 1300000, i.f.v.s.num = 1300000,
                 # flows
                 si.m.flow = 0, vi.m.flow = 0, sv.m.flow = 0,
                 si.f.flow = 0, vi.f.flow = 0, sv.f.flow = 0)

control <- control.dcm(nsteps = (28*365), new.mod = Vaccination)

mod <- dcm(param, init, control)
mod
```


```{r}
# Vaccination Scenario 2.) Catch-up Vaccination increased from        
param2 <- param.dcm( tau.s = 0.74, tau.v = 0.31, ce.m = (5/365),
                    nu = (0.01/365), mu.ue = (0.0025/365), mu = (0.005/365),
                    dur.inf.s.a = (3*365), dur.inf.s.s= (1.5*365),
                    dur.inf.v.a = (3*365), dur.inf.v.s = (1.5*365),
                    age.in = (1/(8*365)), age.out = (1/(11*365)),
                    omega.m = 0.1, omega.f = 0.40, chi = 0.90,
                    zeta.v = (0.1/365) , zeta.s = (0.1/365), kappa.m = (0.0025/365), kappa.f = (0.0025*4/365))

init2 <- init.dcm(uv.m.ue.num = 1600000, uv.m.e.num = 3800000,
                 i.m.s.a.num = 1300000, i.m.uv.s.num= 1300000,
                 v.m.ue.num = 304000, v.m.e.num = 304000, 
                 i.m.v.a.num = 1300000, i.m.v.s.num = 1300000,
                 uv.f.ue.num = 1700000, uv.f.e.num = 3800000, 
                 i.f.s.a.num = 3000000, i.f.uv.s.num = 3000000,
                 v.f.ue.num = 240000, v.f.e.num = 240000, 
                 i.f.v.a.num = 1300000, i.f.v.s.num = 1300000,
                 si.m.flow = 0, vi.m.flow = 0, sv.m.flow = 0,
                 si.f.flow = 0, vi.f.flow = 0, sv.f.flow = 0)

control2 <- control.dcm(nsteps = (28*365), new.mod = Vaccination)

mod2 <- dcm(param2, init2, control2)
mod2
```

Plotting Compartments and Flows
```{r Vaccination Scenario 1}
mod <- mutate_epi(mod, m.num = uv.m.ue.num + uv.m.e.num + i.m.s.a.num + i.m.uv.s.num+ v.m.ue.num + v.m.e.num + i.m.v.a.num + i.m.v.s.num + uv.m.e.num)

mod <- mutate_epi(mod, f.num = uv.f.ue.num + uv.f.e.num + i.f.s.a.num + i.f.uv.s.num + v.f.ue.num + v.f.e.num + i.f.v.a.num + i.f.v.s.num + uv.f.e.num)

mod <- mutate_epi(mod, i.m.num = i.m.s.a.num + i.m.uv.s.num+ i.m.v.a.num + i.m.v.s.num)
mod <- mutate_epi(mod, i.f.num = i.f.s.a.num + i.f.uv.s.num + i.f.v.a.num + i.f.v.s.num)

mod <- mutate_epi(mod, m.prev = i.m.num / m.num)
mod <- mutate_epi(mod, f.prev = i.f.num / f.num)
data <- as.data.frame(mod)

par(mfrow = c(1,2))
plot(mod, y = "m.prev", main = "Proportional Prevalence for Males")
plot(mod, y = "f.prev", main = "Proportional Prevalence for Females")

par(mfrow = c(1,2))
plot(mod, y = "i.m.num", main = "Prevalence for Males")
plot(mod, y = "i.f.num", main = "Prevalence for Females")

par(mfrow = c(1,2))
plot(mod, y = "si.m.flow", main = "si.Males")
plot(mod, y = "si.f.flow", main = "si.Females")

par(mfrow = c(1,2))
plot(mod, y = "vi.m.flow", main = "vi.Males")
plot(mod, y = "vi.f.flow", main = "vi.Females")
```

Plotting Compartments and Flows
```{r Vaccination Scenario 2}
mod2 <- mutate_epi(mod2, m.num = uv.m.ue.num + uv.m.e.num + i.m.s.a.num + i.m.uv.s.num+ v.m.ue.num + v.m.e.num + i.m.v.a.num + i.m.v.s.num + uv.m.e.num)

mod2 <- mutate_epi(mod2, f.num = uv.f.ue.num + uv.f.e.num + i.f.s.a.num + i.f.uv.s.num + v.f.ue.num + v.f.e.num + i.f.v.a.num + i.f.v.s.num + uv.f.e.num)

mod2 <- mutate_epi(mod2, i.m.num = i.m.s.a.num + i.m.uv.s.num+ i.m.v.a.num + i.m.v.s.num)
mod2 <- mutate_epi(mod2, i.f.num = i.f.s.a.num + i.f.uv.s.num + i.f.v.a.num + i.f.v.s.num)

mod2 <- mutate_epi(mod2, m.prev = i.m.num / m.num)
mod2 <- mutate_epi(mod2, f.prev = i.f.num / f.num)
data <- as.data.frame(mod2)

par(mfrow = c(1,2))
plot(mod, y = "m.prev", main = "Proportional Prevalence for Males")
plot(mod, y = "f.prev", main = "Proportional Prevalence for Females")

par(mfrow = c(1,2))
plot(mod, y = "i.m.num", main = "Prevalence for Males")
plot(mod, y = "i.f.num", main = "Prevalence for Females")

par(mfrow = c(1,2))
plot(mod, y = "si.m.flow", main = "si.Males")
plot(mod, y = "si.f.flow", main = "si.Females")

par(mfrow = c(1,2))
plot(mod, y = "vi.m.flow", main = "vi.Males")
plot(mod, y = "vi.f.flow", main = "vi.Females")
```
Couple of issues with how this output is now.
We are substainly decreasing the number of infected, but the proportional prevalence is almost unchanged. I think this has to do with the inflow and outflows of each compartment.


```{r Tom's Vaccine Scenarios}
# Baseline
# Scenario 1 - decrease sexual contacts for males and females by 50% (possible through condom usage)
#Chaging c_m and c_f from 0.014 to 0.007
df <- as.data.frame(mod)

param1 <- param
param1$ce.m <- param1$ce.m * 0.5
mod1 <- dcm(param1, init, control)
df1 <- as.data.frame(mod)
#Infections averted for males in scenario 1
baseline_inf_m <- sum(df$si.m.flow)
scen1_inf_m <- sum(df1$si.m.flow)
inf_avert1_m <- baseline_inf_m - scen1_inf_m
#Infections averted for females in scenario 1
baseline_inf_f <- sum(df$si.f.flow)
scen1_inf_f <- sum(df1$si.f.flow)
inf_avert1_f <- baseline_inf_f - scen1_inf_f

#Scenario 2 - increasing omega or the number fully vaccinated (possible through awareness campaigns)
#Changing omega from 

baseline_inf <- sum(df$si.flow)
param2 <- param
param2$omega.m <- param2$omega.m * 0.5
param2$omega.f <- param2$omega.f * 0.5
mod2 <- dcm(param2, init, control)
df2 <- as.data.frame(mod2)
scen2_inf <- sum(df2$si.flow)
inf_avert2 <- baseline_inf - scen2_inf
#Infections averted for males in scenario 1
scen2_inf_m <- sum(df2$si.m.flow)
inf_avert2_m <- baseline_inf_m - scen2_inf_m
#Infections averted for females in scenario 1
scen2_inf_f <- sum(df2$si.f.flow)
inf_avert2_f <- baseline_inf_f - scen2_inf_f

#Scenario 3 - increase chi by through increasing the number protected 50% (better vaccine scenario)
#Changing chi from 0.9 to 0.95

param3 <- param
param3$chi <- param3$chi * 1.5
mod3 <- dcm(param3, init, control)
df3 <- as.data.frame(mod3)
scen3_inf <- sum(df3$si.flow)
inf_avert3 <- baseline_inf - scen3_inf
#Infections averted for males in scenario 1
scen3_inf_m <- sum(df3$si.m.flow)
inf_avert3_m <- baseline_inf_m - scen3_inf_m
#Infections averted for females in scenario 1
scen3_inf_f <- sum(df3$si.f.flow)
inf_avert3_f <- baseline_inf_f - scen3_inf_f

# Print numerical results for males
print(c(baseline_inf_m, scen1_inf_m, scen2_inf_m, scen3_inf_m))
print(c(inf_avert1_m, inf_avert2_m, inf_avert3_m))

# Print numerical results for females
print(c(baseline_inf_f, scen1_inf_f, scen2_inf_f, scen3_inf_f))
print(c(inf_avert1_f, inf_avert2_f, inf_avert3_f))
```

```{r}
# Plot results
par(mfrow = c(2,3))
plot(mod1, y = "si.m.flow", main = "Incidence for Males (Scenario 1)")
plot(mod2, y = "si.m.flow", main = "Incidence for Males (Scenario 2)")
plot(mod3, y = "si.m.flow", main = "Incidence for Males(Scenario 3)")

plot(mod1, y = "si.f.flow", main = "Incidence for Females (Scenario 1)")
plot(mod2, y = "si.f.flow", main = "Incidence for Females (Scenario 2)")
plot(mod3, y = "si.f.flow", main = "Incidence for Females (Scenario 3)")
```


```{r TOM's Contour Plot Code}
# define two parameters that should vary
kappa.m <- seq(0.1, 0.2, 0.05)
kappa.f <- seq(0.3, 0.4, 0.05)

# create a grid of interaction parameter values
# each row of grid correspond to unique combination of each parameter
grid <- expand.grid(kappa.m = kappa.m,
                    kappa.f = kappa.f)
head(grid, 25)
table(grid)

# this is length(kappa.m) x length(kappa.f) unique combinations
nrow(grid)

param <- param.dcm( tau.s = 0.74, tau.v = 0.31, ce.m = (5/365),
                    nu = (0.01/365), mu.ue = (0.0025/365), mu = (0.005/365),
                    dur.inf.s.a = (3*365), dur.inf.s.s= (1.5*365),
                    dur.inf.v.a = (3*365), dur.inf.v.s = (1.5*365),
                    age.in = (1/(8*365)), age.out = (1/(11*365)),
                    omega.m = 0.1, omega.f = 0.40, chi = 0.90,
                    zeta.v = (0.1/365) , zeta.s = (0.1/365), kappa.m = grid$kappa.m, kappa.f = grid$kappa.f)

#kappa.m = (0.0025/365), kappa.f = (0.0025*4/365)

mod <- dcm(param, init, control)
mod <- mutate_epi(mod, i.m.num = i.m.s.a.num + i.m.uv.s.num+ i.m.v.a.num + i.m.v.s.num)
mod <- mutate_epi(mod, i.f.num = i.f.s.a.num + i.f.uv.s.num + i.f.v.a.num + i.f.v.s.num)
mod <- mutate_epi(mod, si.flow = si.m.flow + si.f.flow)

# create a data frame that groups data by parameter set (run)
# then calculates cumulative incidence in each set
# then adds in the values of the two varying parameters
df2 <- group_by(df, run) %>%
  summarise(cumlinc = sum(si.flow)) %>%
  cbind(kappa.m = grid$kappa.m) %>%
  cbind(kappa.f = grid$kappa.f)
head(df2)

# fancy contour plot; lots of graphics options to explore!
ggplot(df2, aes(kappa.m, kappa.f)) +
  geom_raster(aes(fill = cumlinc), interpolate = TRUE) +
  geom_contour(aes(z = cumlinc), col = "white", alpha = 0.5, lwd = 0.5) +
  geom_text_contour(aes(z = cumlinc), stroke = 0.1) +
  theme_minimal() +
  scale_y_continuous(expand = c(0, 0)) +
  scale_x_continuous(expand = c(0, 0)) +
  labs(x = "Kappa M", y = "Kappa F") +
  scale_fill_viridis(discrete = FALSE, alpha = 1, option = "D", direction = 1)

ggsave("example.pdf")
```



```{r}
# Lexi 
#Scenario: Enhanced vaccine uptake and reduced transmission rates due to preventative measures and a successful vaccination campaign. 

# Define new parameters for enhanced vaccination scenario
param_enhanced_vax <- param.dcm(
  tau.s = 0.5, # Reduced transmission for susceptible
  tau.v = 0.2, # Reduced transmission for vaccinated
  ce.m = (5/365), 
  nu = (0.01/365), 
  mu.ue = (0.0025/365), 
  mu = (0.005/365),
  dur.inf.s.a = (3*365), 
  dur.inf.s.s= (1.5*365),
  dur.inf.v.a = (3*365), 
  dur.inf.v.s = (1.5*365),
  age.in = (1/(8*365)), 
  age.out = (1/(11*365)),
  omega.m = 0.9,  # Increasing proportion of males vaccinated to 90%
  omega.f = 0.85,  # Increased proportion of females vaccinated to 90%
  chi = 0.90, zeta.v = (0.1/365), zeta.s = (0.1/365), kappa = (0.0025/365)
)

# Run the model with new parameters
control_enhanced_vax <- control.dcm(nsteps = (28*365), new.mod = Vaccination)
mod_enhanced_vax <- dcm(param_enhanced_vax, init, control_enhanced_vax)

mod_enhanced_vax <- mutate_epi(mod_enhanced_vax, m.num = uv.m.ue.num + uv.m.e.num + i.m.s.a.num + i.m.uv.s.num+ v.m.ue.num + v.m.e.num + i.m.v.a.num + i.m.v.s.num + uv.m.e.num)

mod_enhanced_vax <- mutate_epi(mod_enhanced_vax, f.num = uv.f.ue.num + uv.f.e.num + i.f.s.a.num + i.f.uv.s.num + v.f.ue.num + v.f.e.num + i.f.v.a.num + i.f.v.s.num + uv.f.e.num)

mod_enhanced_vax<- mutate_epi(mod_enhanced_vax, i.m.num = i.m.s.a.num + i.m.uv.s.num+ i.m.v.a.num + i.m.v.s.num)
mod_enhanced_vax <- mutate_epi(mod_enhanced_vax, i.f.num = i.f.s.a.num + i.f.uv.s.num + i.f.v.a.num + i.f.v.s.num)

mod_enhanced_vax <- mutate_epi(mod_enhanced_vax, m.prev = i.m.num / m.num)
mod_enhanced_vax <- mutate_epi(mod_enhanced_vax, f.prev = i.f.num / f.num)


# Plot results
data_enhanced_vax <- as.data.frame(mod_enhanced_vax)
par(mfrow = c(1, 2))
plot(mod_enhanced_vax, y = "m.prev", main = "Proportional Prevalence for Males")
plot(mod_enhanced_vax, y = "f.prev", main = "Proportional Prevalence for Females")

par(mfrow = c(1, 2))
plot(mod_enhanced_vax, y = "si.m.flow", main = "si.Males")
plot(mod_enhanced_vax, y = "si.f.flow", main = "si.Females")

# Notes: Steady proportional prevalence for both males and females and the number of susceptible individuals for males and females decline over time. 

par(mfrow = c(1,2))
plot(mod_enhanced_vax, y = "i.m.num", main = "Prevalence for Males")
plot(mod_enhanced_vax, y = "i.f.num", main = "Prevalence for Females")

# Notes: Decreasing prevalence

par(mfrow = c(1,2))
plot(mod_enhanced_vax, y = "vi.m.flow", main = "vi.Males", legend='full')
plot(mod_enhanced_vax, y = "vi.f.flow", main = "vi.Females", legend='full')
```

